# Site settings
title: Owen Craig
subtitle: Development at the speed of something something
site: owencraig.com
email: owen@owencraig.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://owencraig.com" # the base hostname & protocol for your site
twitter_username: owencraig
github_username:  owencraig

# Github repositories
github_repo_url: https://github.com/owencraig/owencraig.github.io/

# Build settings
markdown: kramdown

# Disqus Comments
disqus_short_name: owencraigcom
disqus_show_comment_count: true

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap