# Site settings
title: Owen Craig
subtitle: Development at the speed of something something
site: owencraig.com
email: owen@owencraig.com
description: Software development at the speed of something something
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://owencraig.com" # the base hostname & protocol for your site

# social media
twitter_username: owencraig
github_username:  owencraig
linkedin_username: owendrcraig
feed_url: http://feeds.feedburner.com/OwenCraig

# Github repositories
github_repo_url: https://github.com/owencraig/owencraig.github.io/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Disqus Comments
disqus_short_name: owencraigcom
disqus_show_comment_count: true

# google analytics
google_analytics_tracking_id: UA-55609937-1

paginate: 20
paginate_path: "page/:num"
permalinks: :title/

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts