# Site settings
title: Owen Craig
subtitle: Development at the speed of something something
site: owencraig.com
email: owen@owencraig.com
description: > # this means to ignore newlines until "baseurl:"
  Software development information and opinons
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://owencraig.com" # the base hostname & protocol for your site

# social media
twitter_username: owencraig
github_username:  owencraig
linkedin_username: owendrcraig

# Github repositories
github_repo_url: https://github.com/owencraig/owencraig.github.io/

# Build settings
markdown: kramdown

# Disqus Comments
disqus_short_name: owencraigcom
disqus_show_comment_count: true

permalinks: /:title/

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap